services:
  - type: web
    name: f1-api
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
    healthCheckPath: /status
    healthCheckIntervalSeconds: 10
    healthCheckTimeoutSeconds: 5
