services:
  - type: web
    name: f1-api
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
    healthCheckPath: /
